### ISSUE TITLE
Translations seem to cause trouble in multiplayer, disconnecting joining player

### ISSUE THREAD

**Issue by Bilka2** [raiguard/Factorio-Flib#45]
See https://forums.factorio.com/viewtopic.php?p=569067#p569067 and possibly the related topic linked in the posts in the topic.

**Comment by raiguard** [comment]
Yeah, this is a known issue. I have some ideas on how to fix it, but I am unable to replicate the issue myself so I can't properly test it. Once I get my laptop in August I'll be able to properly test it and fix it.

**Comment by Hornwitser** [comment]
The issue is fairly simple. You translate some 50 strings in one tick by default. This gets sent in a single tick as a 30kB large localized string with a 30kB large result payload:

![image](https://user-images.githubusercontent.com/14362102/175545387-e2df3377-0740-4c0b-acd0-792a10605a6b.png)

This is then packed into a 60kB heartbeat that is then split into 125 fragments of 516 bytes UDP packets that are all sent at once (i.e. at line rate):

![image](https://user-images.githubusercontent.com/14362102/175545987-1f728e98-517a-44f9-b80f-49ea3700bf26.png)

Over my loopback it's going at an instantaneous transfer rate of ~550 Mbit/s, though there's no reason a Gbit/s ethernet controller couldn't send it at 1 Gbit/s. If this was going over the internet instead of loopback this packet burst would likely hit a modem with a significantly slower line rate than 1 Gbit/s and overflow its receive/send buffer and cause one or more of the fragments to be lost. If any part of a fragmented heartbeat is lost then the heartbeat is resent in full as there is no per fragment resend mechanism for heartbeats, and if every time it's resent it causes the same buffer to overflow and drop the same fragments then the client times out as it'll never receive all the part of the fragmented heartbeat.

To put it into perspective on how grossly out of line it is to send 60 kB of data in one tick, before 0.18.7 all windows clients would drop out of the game if you sent more than 8kB of data in two ticks. The current translation request size is 10x higher than what is reasonable for the protocol.

**Comment by raiguard** [comment]
Thanks for the detailed analysis @Hornwitser. I have decided to remove the nesting entirely, and do a hardcoded five strings per translation. I don't have the tools to test how much network traffic this generates, but I'm going to send it to a few people to see if it solves their issues.
